name: "Deploy to GitHub Pages"
on: push
jobs: 
  deploy:
    name: Deploy to Github-Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Configure Git Username
      run: |
        git config --global user.name ${{ secrets.NAME }}
        git config --global user.email ${{ secrets.EMAIL }}
    - name: Authenticate Git
      run: |
        git config --global user.actor ${{ secrets.ACTOR }}
        git config --global user.token ${{ secrets.GITHUB_TOKEN }}

    - name: Install Dependencies
      run: npm install

    - name: Deploy
      run: npm run deploy
